"""Preset column/header definitions shared across the application."""

from __future__ import annotations

DEFAULT_PRESET_NAME = "Default"

DEFAULT_PRESETS = {
    DEFAULT_PRESET_NAME: {
        "datalog_columns": [
            0,
            1,
            3,
            4,
            5,
            6,
            39,
            40,
            41,
            42,
            78,
            79,
            82,
            83,
            8,
            9,
            10,
            11,
            12,
            13,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            106,
            107,
            108,
            109,
            110,
            111,
            112,
            113,
            114,
        ],
        "datalog_headers": [
            "Date/Time",
            "Flow (g/s)",
            "Cat 1 Inlet Analogue ETAS 1 (-)",
            "Cat 1 Outlet Analogue ETAS 2 (-)",
            "Cat 2 Inlet Analogue ETAS 3 (-)",
            "Cat 2 Outlet Analogue ETAS 4 (-)",
            "NB Sensor Cat 1 Mid Brick (V)",
            "NB Sensor Cat 1 Outlet (V)",
            "NB Sensor Cat 2 Mid Brick (V)",
            "NB Sensor Cat 2 Outlet (V)",
            "Cat 1 Inlet Digital ETAS 1 (-)",
            "Cat 1 Outlet Digital ETAS 2 (-)",
            "Cat 2 Inlet Digital ETAS 3 (-)",
            "Cat 2 Outlet Digital ETAS 4 (-)",
            "Cat 1 Inlet Gas Temperature (°C)",
            "Cat 1 Bed 1 Centre (°C)",
            "Cat 1 Bed 2 Centre (°C)",
            "Cat 1 Bed 2 Circumference Door Side (°C)",
            "Cat 1 Midpoint Gas Temperature (°C)",
            "Cat 1 Bed 3 Centre (°C)",
            "Cat 1 Bed 4 Centre (°C)",
            "Cat 1 Bed 5 Centre (°C)",
            "Cat 1 Bed 5 Circumference Door Side (°C)",
            "Cat 1 Outlet Gas Temperature (°C)",
            "Cat 2 Inlet Gas Temperature (°C)",
            "Cat 2 Bed 1 Centre (°C)",
            "Cat 2 Bed 2 Centre (°C)",
            "Cat 2 Bed 2 Circumference Door Side (°C)",
            "Cat 2 Midpoint Gas Temperature (°C)",
            "Cat 2 Bed 3 Centre (°C)",
            "Cat 2 Bed 4 Centre (°C)",
            "Cat 2 Bed 5 Centre (°C)",
            "Cat 2 Bed 5 Circumference Door Side (°C)",
            "Cat 2 Outlet Gas Temperature (°C)",
            "Water Concentration (%)",
            "CH4 Concentration (ppm)",
            "CO Concentration (%)",
            "NO Concentration (ppm)",
            "C3H6 Concentration (ppm)",
            "CO2 Concentration(%)",
            "NH3 Concentration (ppm)",
            "N2O Concentration (ppm)",
            "NO2 Concentration (ppm)",
        ],
        "mfc_columns": [
            0,
            2,
            3,
            11,
            8,
            10,
            4,
            13,
            14,
            22,
            24,
            21,
            15,
        ],
        "mfc_headers": [
            "Date/Time",
            "005 NG Injection (SLPM)",
            "005 Air Injection (SLPM)",
            "005 O2 Injection (SLPM)",
            "006 Air Injection (SLPM)",
            "006 NG Injection (SLPM)",
            "006 O2 Injection (SLPM)",
            "005 NG Injection Set Point (SLPM)",
            "005 Air Injection Set Point (SLPM)",
            "005 O2 Injection Set Point (SLPM)",
            "006 Air Injection Set Point (SLPM)",
            "006 NG Injection Set Point (SLPM)",
            "006 O2 Injection Set Point (SLPM)",
        ],
    }
}
